### PR TITLE
No more OpenCV for homography

### PR DESCRIPTION
**Pull request by CyrCom**
I got the correct implementation finally, it can still use OpenCV if you want, it is just a matter or asking homography always from (0,0) coordinates and then translate in place. This PR doesn't use OpenCV anymore, if you agree I will update examples in consequence.
Cheers !

### CODE REVIEW

**Comment by roymacdonald** [comment]
great! sure, getting rid of openCV is a good thing as we won't need to carry such a huge library.
Yes please, update the examples.
cheers

**Comment by CyrCom** [comment]
Ok, right.
Then I think you will agree on removing #include "stdio.h" from examples also ;)

**Comment by roymacdonald** [comment]
sure, do what ever you think is right! :D

**Comment by roymacdonald** [comment]
Just let me know once you are ready with the updates. 
Thanks

**Comment by CyrCom** [comment]
Oh, yes that's fine for now, tested and well.
Maybe I will think about the ofEvents that I don't understand the advantage
here.
When you can call getcorner() why bother make a event listener and so on ?
Things are called as many times in both way.
But that's more a clean up than an optimization also. Maybe I'm going too
far, but I really love it direct and simple. Like the XML saving is already
too much for me ^^ I like that an add-on has one task and depends on itself
only.
Next I'm gonna try to add 'corners', I read that the same method with
matrices can deal with more vertices. We'll see.
But I'll try to focus on my whole project and not drift, it's about
video-mapping with a network of RPI connected to projectors and have cues
and all. And that has to be 100% solid and discreet because it's mainly for
theater. That's why I have to know all the code I use very well and be
confident about it.
Anyway, you're good to pull request, the rest will come later as
improvements.
Bye :)

Le 6 juil. 2018 9:40 PM, "Roy Macdonald" <notifications@github.com> a
écrit :

Just let me know once you are ready with the updates.
Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/roymacdonald/ofxGLWarper/pull/15#issuecomment-403128360>,
or mute the thread

**Comment by roymacdonald** [comment]
Superb! thanks.
The events were added by other contributor. These are useful on instances where you want  to trigger something when a corner is moved, such as rendering again in an render-upon-request environment. It is actually quite useful.
The XML saving is absolutely needed, from my point of view. If you are mapping something you'll want to save that state so you can start from that same point afterwards. Otherwise, if you cant save and quit the app you'll loose everything you did! It might be a good idea to move to ofXml instead of ofxXmlSettings, or even to ofJSON. This move would remove the dependency on ofxXmlSettings which would be good.

**Comment by roymacdonald** [comment]
@CyrCom I just removed the ofxXmlSettings dependency.

**Pull request merged**
